# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@anthropic-ai/claude-agent-sdk-darwin-arm64@0.3.251" = fetchurl {
    url = "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-darwin-arm64/-/claude-agent-sdk-darwin-arm64-0.3.251.tgz";
    hash = "sha512-C23h+Dbddcc4gai95+lhm4/94am2IOq+bf3IdEDDS7EPqDQqajo2s5q1/ZSwq9rOc0RJLT7Ws72ZCzYJh67KSg==";
  };
  "@anthropic-ai/claude-agent-sdk-darwin-x64@0.3.251" = fetchurl {
    url = "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-darwin-x64/-/claude-agent-sdk-darwin-x64-0.3.251.tgz";
    hash = "sha512-HrLnb3ggk+vMbymUvbosgPmxWp4W6Ot+0mNVjoBYDn5OZrTV3C3LRtbWf7jwcGyKMcg0xJf0AqiudQ2BRrlr8A==";
  };
  "@anthropic-ai/claude-agent-sdk-linux-arm64-musl@0.3.251" = fetchurl {
    url = "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-arm64-musl/-/claude-agent-sdk-linux-arm64-musl-0.3.251.tgz";
    hash = "sha512-RTUf7TPBUkQ6oV3pDkEdcD47I0uH0ZpvmZlXHnrLGznFqyLr+7XHupOxUMJD0Jwm9v5qeqpNiPAYB0dL4RYiHg==";
  };
  "@anthropic-ai/claude-agent-sdk-linux-arm64@0.3.251" = fetchurl {
    url = "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-arm64/-/claude-agent-sdk-linux-arm64-0.3.251.tgz";
    hash = "sha512-3E27F5j82EWOyEniRW7crmo0jWYYQmPDdP52jWq6Y6aytiyYIdUFMEGZZ6chVHNlZiU7GsjTa3teKk2xlQ68lQ==";
  };
  "@anthropic-ai/claude-agent-sdk-linux-x64-musl@0.3.251" = fetchurl {
    url = "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-x64-musl/-/claude-agent-sdk-linux-x64-musl-0.3.251.tgz";
    hash = "sha512-SzXrdy7jjrjJIuTG+VMRAY0YZ3G/8w21WuhAozwnvnEUAPo6NDv6lgFinu7NO8J6CPE+MK2sGze6JeCF+ljgUg==";
  };
  "@anthropic-ai/claude-agent-sdk-linux-x64@0.3.251" = fetchurl {
    url = "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-x64/-/claude-agent-sdk-linux-x64-0.3.251.tgz";
    hash = "sha512-qCD87XPjcNM1u4ukqmcgpHDl3Y6l+cW8j7kPzH91Y5yLBYJ5xYZA2KtJ7AYNEPOteVyOGJw/efmva0S8CRr0fg==";
  };
  "@anthropic-ai/claude-agent-sdk-win32-arm64@0.3.251" = fetchurl {
    url = "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-win32-arm64/-/claude-agent-sdk-win32-arm64-0.3.251.tgz";
    hash = "sha512-FH1ZLcyc97ie3h7CSlIxA1ppXILgf0V8sFQrWnHyKBrthJXQkMHXhsTq9OZV/2KhXslNf2hTe0gHpZ1nCL1Gmg==";
  };
  "@anthropic-ai/claude-agent-sdk-win32-x64@0.3.251" = fetchurl {
    url = "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-win32-x64/-/claude-agent-sdk-win32-x64-0.3.251.tgz";
    hash = "sha512-/jmtFIvfF0UFMxSZ8WV2Aus8aGA3+8Ft6AHvWuBJkY5jM2ubfqi6GnBjKCAL831TTllp2rKZlViANtWWRBvpvg==";
  };
  "@anthropic-ai/claude-agent-sdk@0.3.251" = fetchurl {
    url = "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk/-/claude-agent-sdk-0.3.251.tgz";
    hash = "sha512-DqSi8mH2tQYRlVV0G+lJnQ/WbjJZ/a+8cJ3vPuYoqh8esIIvXHm1ZOXV1UPGsFYRnbBytEoiSGitguEXd+sQ+Q==";
  };
  "@anthropic-ai/sdk@0.122.0" = fetchurl {
    url = "https://registry.npmjs.org/@anthropic-ai/sdk/-/sdk-0.122.0.tgz";
    hash = "sha512-GGPNftt0caaz9MDlmNQGHX8855Ojaduyy5pm9Sm1h7HalCn0cWNb5/bweadJF+4yzbal+QL6ztBa09WAAOzLmQ==";
  };
  "@babel/runtime@7.29.7" = fetchurl {
    url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.29.7.tgz";
    hash = "sha512-Nq8OhGWiZIZGV6hLHoyAKLLcJihP/xFeBMGJoUrxTX2psI8dCifzLhZISFb+VWS3wFMRDmCGw5R+dOySCqPLhw==";
  };
  "@effect/platform-bun@4.0.0-rc.112" = fetchurl {
    url = "https://registry.npmjs.org/@effect/platform-bun/-/platform-bun-4.0.0-rc.112.tgz";
    hash = "sha512-Y5n2HhV/vsbrJls9ukX42RL7zqXQxISHegWFsP9njsCyDmGTnq7QYSO82rglwrLPwtTrv5dkSRTuGw4+oXxgMg==";
  };
  "@effect/platform-node-shared@4.0.0-rc.112" = fetchurl {
    url = "https://registry.npmjs.org/@effect/platform-node-shared/-/platform-node-shared-4.0.0-rc.112.tgz";
    hash = "sha512-ttjz0xKamFN7vL8pNDYVwddJLjZvqKePc05djlz2VcdaKbLsnYbtMnL1rbOfHgEnIUSHGh7FkjaN4DM1Ov81sQ==";
  };
  "@hono/node-server@2.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@hono/node-server/-/node-server-2.1.1.tgz";
    hash = "sha512-ELuehkj5VCBdgEw9zs+ivkKwyzzUCSQuE96YmiPvn1ECBoZCczbFXJLeEGMTYjphP6gydh4pHMqEYPVMYUVgQg==";
  };
  "@modelcontextprotocol/sdk@1.30.0" = fetchurl {
    url = "https://registry.npmjs.org/@modelcontextprotocol/sdk/-/sdk-1.30.0.tgz";
    hash = "sha512-xKd8OIzlqNzcqcNumGAa6g+PW2kjD5vrpcKOnfldAUPP3j7lnqMPwlTXQm8gF+UwH72z0lqaRbjr9hqGz0eITA==";
  };
  "@msgpackr-extract/msgpackr-extract-darwin-arm64@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@msgpackr-extract/msgpackr-extract-darwin-arm64/-/msgpackr-extract-darwin-arm64-3.0.4.tgz";
    hash = "sha512-LCkGo6JDfaBhgST7UpPWgNgLINpcpabaHfyz5OBx75nUYxBsaEPxjnyNjWpeb/xBup/682QnBfRBy2/LvPutZQ==";
  };
  "@msgpackr-extract/msgpackr-extract-darwin-x64@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@msgpackr-extract/msgpackr-extract-darwin-x64/-/msgpackr-extract-darwin-x64-3.0.4.tgz";
    hash = "sha512-zExlW9zUJKZH/tOtVMttwjKa4Xm/3KcNjnE3dPN92uCktwavMxpgCA3MoJK/DOnTWsQgo224OaST27/mPNAf+w==";
  };
  "@msgpackr-extract/msgpackr-extract-linux-arm64@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@msgpackr-extract/msgpackr-extract-linux-arm64/-/msgpackr-extract-linux-arm64-3.0.4.tgz";
    hash = "sha512-dgX0P/9wGPJeHFBG+ZmhgE6bmtMt7NP5CRBGyyktpopdk/mW4POnrpQsSLtKI1dwpc+pPLuXHDh6vvskyQE/sw==";
  };
  "@msgpackr-extract/msgpackr-extract-linux-arm@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@msgpackr-extract/msgpackr-extract-linux-arm/-/msgpackr-extract-linux-arm-3.0.4.tgz";
    hash = "sha512-Tg3yX65f5GbtXLkrYEHE5oibZG9epyYWas7FogTTEJeDEF9JlXJzKgXaNhT3UXlTOeA+AfZpYZYZ0uPj7Cfquw==";
  };
  "@msgpackr-extract/msgpackr-extract-linux-x64@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@msgpackr-extract/msgpackr-extract-linux-x64/-/msgpackr-extract-linux-x64-3.0.4.tgz";
    hash = "sha512-8TNXMEjJc3QEy7R/x1INhgiU+XakDAFUzBhaz7+Rbrs8NH5UQeHQxxmzsSBJGyV6I1jW79undiQm8tOI+D+8FQ==";
  };
  "@msgpackr-extract/msgpackr-extract-win32-x64@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@msgpackr-extract/msgpackr-extract-win32-x64/-/msgpackr-extract-win32-x64-3.0.4.tgz";
    hash = "sha512-CmCXPQrkbwExx3j946/PtHWHbYJiCRBRDl4BlkRQcJB/YOwQxJRTpoo7aTsortjgoJ1x7opzTSxn7C+ASSLVjQ==";
  };
  "@opentui/core-darwin-arm64@0.5.9" = fetchurl {
    url = "https://registry.npmjs.org/@opentui/core-darwin-arm64/-/core-darwin-arm64-0.5.9.tgz";
    hash = "sha512-YcpWGD8GwoO3UYYw0kLDI4qof3ElSwWW5M3fNG+Kw87BSjCa5frZqak5xebdZ/XU5Xsk+BjgbBsxbzo9yrIjZQ==";
  };
  "@opentui/core-darwin-x64@0.5.9" = fetchurl {
    url = "https://registry.npmjs.org/@opentui/core-darwin-x64/-/core-darwin-x64-0.5.9.tgz";
    hash = "sha512-xgdZwgcwlDCqi0WPCS1d0GVSd+oKDFX+UVE1ZPei8u8W3pirXGSExxVHNku7QbEYCRvpCeMtoKIa6xN9cVTsoQ==";
  };
  "@opentui/core-linux-arm64-musl@0.5.9" = fetchurl {
    url = "https://registry.npmjs.org/@opentui/core-linux-arm64-musl/-/core-linux-arm64-musl-0.5.9.tgz";
    hash = "sha512-A7GW4NCTInj2vy3X2gVO2Sm8jllgdLxwPdOklPqyl+xqivQtyG9qwS5YXoCk9fBJt10ORhYKETEjYEnIE5xvMQ==";
  };
  "@opentui/core-linux-arm64@0.5.9" = fetchurl {
    url = "https://registry.npmjs.org/@opentui/core-linux-arm64/-/core-linux-arm64-0.5.9.tgz";
    hash = "sha512-vHBiJp69wMaL+fRMDpnXCCIpPyQRPZEWCWBatnblUUGIWUseqeQlaPow6ljHSbgAd/GjygAf4tFCyTqNT2ezZA==";
  };
  "@opentui/core-linux-x64-musl@0.5.9" = fetchurl {
    url = "https://registry.npmjs.org/@opentui/core-linux-x64-musl/-/core-linux-x64-musl-0.5.9.tgz";
    hash = "sha512-J4wQs1OMPZ4hR93Op1C/BLFmIta2mUJm4M7djevlgcWcal4RSNO4V8QvUXfogWGci+ADZqEmX2osQQDY5NVJpw==";
  };
  "@opentui/core-linux-x64@0.5.9" = fetchurl {
    url = "https://registry.npmjs.org/@opentui/core-linux-x64/-/core-linux-x64-0.5.9.tgz";
    hash = "sha512-rdw7QVopVHwj6fMrJc7hPGVaYg2V5NBlW3MUfkrQBlUlo/87OC4aYDAh5oRIL1CIFD9LjDdh7hwmUNbn/K9Pcw==";
  };
  "@opentui/core-win32-arm64@0.5.9" = fetchurl {
    url = "https://registry.npmjs.org/@opentui/core-win32-arm64/-/core-win32-arm64-0.5.9.tgz";
    hash = "sha512-OnmEsGLWwsHrm6sTsWSSesu4LGjSV1JNWqCsEItbuitWaqH6rXdSahSc5jMFsS57bZxUyaRz01yAqiZzUSXnVQ==";
  };
  "@opentui/core-win32-x64@0.5.9" = fetchurl {
    url = "https://registry.npmjs.org/@opentui/core-win32-x64/-/core-win32-x64-0.5.9.tgz";
    hash = "sha512-/CnAIfKL7+ZeGLyZoXV5zS71Nd8Zn97RUir2DAIY05MJozmfg5s7XOAdUNYuK1cg5mbwlAuqeAsfbuWUAEe15g==";
  };
  "@opentui/core@0.5.9" = fetchurl {
    url = "https://registry.npmjs.org/@opentui/core/-/core-0.5.9.tgz";
    hash = "sha512-d0EWYyp6djitu1N1R0o75NrLl4TxY3oJEmRNrX9vSKKC5/jriGQdSV6lJmwiB77O0cxtBnPzWztAV79vA1J2fA==";
  };
  "@stablelib/base64@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/@stablelib/base64/-/base64-1.0.1.tgz";
    hash = "sha512-1bnPQqSxSuc3Ii6MhBysoWCg58j97aUjuCSZrGSmDxNqtytIi0k8utUenAwTZN4V5mXXYGsVUI9zeBqy+jBOSQ==";
  };
  "@types/bun@1.4.0" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.4.0.tgz";
    hash = "sha512-K+lZULY23vRgK/CfTjFIV+tyifaNdSMlPh9j+6mQ/cLfpOznLyAuzgV/JQysyECpkBQLVMSyvjlr2fBUSA9wFQ==";
  };
  "@types/node@26.4.0" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-26.4.0.tgz";
    hash = "sha512-faiGnoIrLH/V8cibOMEAZ8pMw6oXqSukl29ra4mN8GdaB2ZewzeaLj+INpV5N+Z1eKWzY+IzaIZH2EIR6YZRNQ==";
  };
  "@types/ws@8.18.1" = fetchurl {
    url = "https://registry.npmjs.org/@types/ws/-/ws-8.18.1.tgz";
    hash = "sha512-ThVF6DCVhA8kUGy+aazFQ4kXQ7E1Ty7A3ypFOe0IcJV8O/M511G99AW24irKrW56Wt44yG9+ij8FaqoBGkuBXg==";
  };
  "accepts@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/accepts/-/accepts-2.0.0.tgz";
    hash = "sha512-5cvg6CtKwfgdmVqY1WIiXKc3Q1bkRqGLi+2W/6ao+6Y7gu/RCwRuAhGEzh5B4KlszSuTLgZYuqFqo5bImjNKng==";
  };
  "ajv-formats@3.0.1" = fetchurl {
    url = "https://registry.npmjs.org/ajv-formats/-/ajv-formats-3.0.1.tgz";
    hash = "sha512-8iUql50EUR+uUcdRQ3HDqa6EVyo3docL8g5WJ3FNcWmu62IbkGUue/pEyLBW8VGKKucTPgqeks4fIU1DA4yowQ==";
  };
  "ajv@8.20.0" = fetchurl {
    url = "https://registry.npmjs.org/ajv/-/ajv-8.20.0.tgz";
    hash = "sha512-Thbli+OlOj+iMPYFBVBfJ3OmCAnaSyNn4M1vz9T6Gka5Jt9ba/HIR56joy65tY6kx/FCF5VXNB819Y7/GUrBGA==";
  };
  "ansi-regex@6.3.0" = fetchurl {
    url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.3.0.tgz";
    hash = "sha512-WpDfL7NO6j7tH88IDBNVdUJxDh9nmCteAVW9dsep846XdwF4naCBK+/tGLX3KJgcpgMRXCFlTM2hKGoK9FsdrQ==";
  };
  "body-parser@2.3.0" = fetchurl {
    url = "https://registry.npmjs.org/body-parser/-/body-parser-2.3.0.tgz";
    hash = "sha512-2cGmJupaNgg+QUwVLAucDuWuoMZ6EX9iHDRswZ5lsNYEmwPaRknMPCLZz07yTzVq/83p4o/wzbDZbBrTvGGTIw==";
  };
  "bun-ffi-structs@0.3.1" = fetchurl {
    url = "https://registry.npmjs.org/bun-ffi-structs/-/bun-ffi-structs-0.3.1.tgz";
    hash = "sha512-3gM7PpVWLyrwxWjcilSiGuhWanhZivvo6l0u573NziPH6f/gwk6McbaYgn7oJWov6pKGRTDbrg94W5DcJsKTtQ==";
  };
  "bun-types@1.4.0" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.4.0.tgz";
    hash = "sha512-iIKw23BspnQQYd3prITOBxeUsxBHnwzX6YJfGMuNOZzeNcMmVqzIIVGRm1l69ogaPQmb4wB6BN8mA5bE9YuC5Q==";
  };
  "bytes@3.1.2" = fetchurl {
    url = "https://registry.npmjs.org/bytes/-/bytes-3.1.2.tgz";
    hash = "sha512-/Nf7TyzTx6S3yRJObOAV7956r8cr2+Oj8AC5dt8wSP3BQAoeX58NoHyCU8P8zGkNXStjTSi6fzO6F0pBdcYbEg==";
  };
  "call-bind-apply-helpers@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/call-bind-apply-helpers/-/call-bind-apply-helpers-1.0.2.tgz";
    hash = "sha512-Sp1ablJ0ivDkSzjcaJdxEunN5/XvksFJ2sMBFfq6x0ryhQV/2b/KwFe21cMpmHtPOSij8K99/wSfoEuTObmuMQ==";
  };
  "call-bound@1.0.4" = fetchurl {
    url = "https://registry.npmjs.org/call-bound/-/call-bound-1.0.4.tgz";
    hash = "sha512-+ys997U96po4Kx/ABpBCqhA9EuxJaQWDQg7295H4hBphv3IZg0boBKuwYpt4YXp6MZ5AmZQnU/tyMTlRpaSejg==";
  };
  "content-disposition@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/content-disposition/-/content-disposition-1.1.0.tgz";
    hash = "sha512-5jRCH9Z/+DRP7rkvY83B+yGIGX96OYdJmzngqnw2SBSxqCFPd0w2km3s5iawpGX8krnwSGmF0FW5Nhr0Hfai3g==";
  };
  "content-type@1.0.5" = fetchurl {
    url = "https://registry.npmjs.org/content-type/-/content-type-1.0.5.tgz";
    hash = "sha512-nTjqfcBFEipKdXCv4YDQWCfmcLZKm81ldF0pAopTvyrFGVbcR6P/VAAd5G7N+0tTr8QqiU0tFadD6FK4NtJwOA==";
  };
  "content-type@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/content-type/-/content-type-2.1.0.tgz";
    hash = "sha512-mj7UPXE0jaqaOsukNZRUEfEi2AcL7C/vwmwcHV0O97eO1E1pxBZuyjlZrx5seTaNBg1U6+o35wpa35Qfcc+7ag==";
  };
  "cookie-signature@1.2.2" = fetchurl {
    url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.2.2.tgz";
    hash = "sha512-D76uU73ulSXrD1UXF4KE2TMxVVwhsnCgfAyTg9k8P6KGZjlXKrOLe4dJQKI3Bxi5wjesZoFXJWElNWBjPZMbhg==";
  };
  "cookie@0.7.2" = fetchurl {
    url = "https://registry.npmjs.org/cookie/-/cookie-0.7.2.tgz";
    hash = "sha512-yki5XnKuf750l50uGTllt6kKILY4nQ1eNIQatoXEByZ5dWgnKqbnqmTrBE5B4N7lrMJKQ2ytWMiTO2o0v6Ew/w==";
  };
  "cors@2.8.6" = fetchurl {
    url = "https://registry.npmjs.org/cors/-/cors-2.8.6.tgz";
    hash = "sha512-tJtZBBHA6vjIAaF6EnIaq6laBBP9aq/Y3ouVJjEfoHbRBcHBAHYcMh/w8LDrk2PvIMMq8gmopa5D4V8RmbrxGw==";
  };
  "cross-spawn@7.0.6" = fetchurl {
    url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
    hash = "sha512-uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
  };
  "debug@4.4.3" = fetchurl {
    url = "https://registry.npmjs.org/debug/-/debug-4.4.3.tgz";
    hash = "sha512-RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==";
  };
  "depd@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/depd/-/depd-2.0.0.tgz";
    hash = "sha512-g7nH6P6dyDioJogAAGprGpCtVImJhpPk/roCzdb3fIh61/s/nPsfR6onyMwkCAR/OlC3yBC0lESvUoQEAssIrw==";
  };
  "detect-libc@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/detect-libc/-/detect-libc-2.1.2.tgz";
    hash = "sha512-Btj2BOOO83o3WyH59e8MgXsxEQVcarkUOpEYrubB0urwnN10yQ364rsiByU11nZlqWYZm05i/of7io4mzihBtQ==";
  };
  "diff@9.0.0" = fetchurl {
    url = "https://registry.npmjs.org/diff/-/diff-9.0.0.tgz";
    hash = "sha512-svtcdpS8CgJyqAjEQIXdb3OjhFVVYjzGAPO8WGCmRbrml64SPw/jJD4GoE98aR7r25A0XcgrK3F02yw9R/vhQw==";
  };
  "dunder-proto@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/dunder-proto/-/dunder-proto-1.0.1.tgz";
    hash = "sha512-KIN/nDJBQRcXw0MLVhZE9iQHmG68qAVIBg9CqmUYjmQIhgij9U5MFvrqkUL5FbtyyzZuOeOt0zdeRe4UY7ct+A==";
  };
  "ee-first@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
    hash = "sha512-WMwm9LhRUo+WUaRN+vRuETqG89IgZphVSNkdFgeb6sS/E4OrDIN7t48CAewSHXc6C8lefD8KKfr5vY61brQlow==";
  };
  "effect@4.0.0-rc.112" = fetchurl {
    url = "https://registry.npmjs.org/effect/-/effect-4.0.0-rc.112.tgz";
    hash = "sha512-wXxwuh1Ywnv4cPRM3Wfa0vDwuOHnZ1TsTgHJkG9XgzND6inhBH9n1vBxhg3iIXOia/OrpmvVmd3lrD4vq6bF3A==";
  };
  "emoji-regex@10.6.0" = fetchurl {
    url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-10.6.0.tgz";
    hash = "sha512-toUI84YS5YmxW219erniWD0CIVOo46xGKColeNQRgOzDorgBi1v4D71/OFzgD9GO2UGKIv1C3Sp8DAn0+j5w7A==";
  };
  "encodeurl@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/encodeurl/-/encodeurl-2.0.0.tgz";
    hash = "sha512-Q0n9HRi4m6JuGIV1eFlmvJB7ZEVxu93IrMyiMsGC0lrMJMWzRgx6WGquyfQgZVb31vhGgXnfmPNNXmxnOkRBrg==";
  };
  "es-define-property@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.1.tgz";
    hash = "sha512-e3nRfgfUZ4rNGL232gUgX06QNyyez04KdjFrF+LTRoOXmrOgFKDg4BCdsjW8EnT69eqdYGmRpJwiPVYNrCaW3g==";
  };
  "es-errors@1.3.0" = fetchurl {
    url = "https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz";
    hash = "sha512-Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==";
  };
  "es-object-atoms@1.1.2" = fetchurl {
    url = "https://registry.npmjs.org/es-object-atoms/-/es-object-atoms-1.1.2.tgz";
    hash = "sha512-HWcBoN6NileqtSydK2FqHbS/LoDd2pqrnQHLyJzBj4kOp/ky2MWMN694xOfkK8/SnUsW2DH7EfyVlydKCsm1Zw==";
  };
  "escape-html@1.0.3" = fetchurl {
    url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
    hash = "sha512-NiSupZ4OeuGwr68lGIeym/ksIZMJodUGOSCZ/FSnTxcrekbvqrgdUxlJOMpijaKZVjAJrWrGs/6Jy8OMuyj9ow==";
  };
  "etag@1.8.1" = fetchurl {
    url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
    hash = "sha512-aIL5Fx7mawVa300al2BnEE4iNvo1qETxLrPI/o05L7z6go7fCw1J6EQmbK4FmJ2AS7kgVF/KEZWufBfdClMcPg==";
  };
  "eventsource-parser@3.1.1" = fetchurl {
    url = "https://registry.npmjs.org/eventsource-parser/-/eventsource-parser-3.1.1.tgz";
    hash = "sha512-EKN1vKAMcZ8MlYMpaNuxN6R9yakzH6uajHcHVTqWJzvu5pWw9DyhbP35HH8MVBQ+dZjAfDxk+A8NiR9KWaXiyQ==";
  };
  "eventsource@3.0.7" = fetchurl {
    url = "https://registry.npmjs.org/eventsource/-/eventsource-3.0.7.tgz";
    hash = "sha512-CRT1WTyuQoD771GW56XEZFQ/ZoSfWid1alKGDYMmkt2yl8UXrVR4pspqWNEcqKvVIzg6PAltWjxcSSPrboA4iA==";
  };
  "express-rate-limit@8.7.0" = fetchurl {
    url = "https://registry.npmjs.org/express-rate-limit/-/express-rate-limit-8.7.0.tgz";
    hash = "sha512-hOwV7WOxXfjRpAM1DSJWZDXx3GhplwD8IfwuwvogD8i1Qnkgosw/H45s4ZnFAUHDAhPjlY9hLBvJhKmGMyY26g==";
  };
  "express@5.2.1" = fetchurl {
    url = "https://registry.npmjs.org/express/-/express-5.2.1.tgz";
    hash = "sha512-hIS4idWWai69NezIdRt2xFVofaF4j+6INOpJlVOLDO8zXGpUVEVzIYk12UUi2JzjEzWL3IOAxcTubgz9Po0yXw==";
  };
  "fast-check@4.9.0" = fetchurl {
    url = "https://registry.npmjs.org/fast-check/-/fast-check-4.9.0.tgz";
    hash = "sha512-7ms6T7SybUev/PQITciI0yLM2pOSFy5zpG8Ty7tQofcVaQUvrMXp6CBwqF6fThLCLOrfBtuHAtwq6Yu4XPCllg==";
  };
  "fast-deep-equal@3.1.3" = fetchurl {
    url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
    hash = "sha512-f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
  };
  "fast-sha256@1.3.0" = fetchurl {
    url = "https://registry.npmjs.org/fast-sha256/-/fast-sha256-1.3.0.tgz";
    hash = "sha512-n11RGP/lrWEFI/bWdygLxhI+pVeo1ZYIVwvvPkW7azl/rOy+F3HYRZ2K5zeE9mmkhQppyv9sQFx0JM9UabnpPQ==";
  };
  "fast-uri@3.1.6" = fetchurl {
    url = "https://registry.npmjs.org/fast-uri/-/fast-uri-3.1.6.tgz";
    hash = "sha512-7Ical1vFEMr0onbVzEDIreM22I4khW+fzyQPwvAFWBp1iwdshSZRsL4jjRvPG9JP1uiqMHRto+YU6R2/CzDz5Q==";
  };
  "finalhandler@2.1.1" = fetchurl {
    url = "https://registry.npmjs.org/finalhandler/-/finalhandler-2.1.1.tgz";
    hash = "sha512-S8KoZgRZN+a5rNwqTxlZZePjT/4cnm0ROV70LedRHZ0p8u9fRID0hJUZQpkKLzro8LfmC8sx23bY6tVNxv8pQA==";
  };
  "forwarded@0.2.0" = fetchurl {
    url = "https://registry.npmjs.org/forwarded/-/forwarded-0.2.0.tgz";
    hash = "sha512-buRG0fpBtRHSTCOASe6hD258tEubFoRLb4ZNA6NxMVHNw2gOcwHo9wyablzMzOA5z9xA9L1KNjk/Nt6MT9aYow==";
  };
  "fresh@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/fresh/-/fresh-2.0.0.tgz";
    hash = "sha512-Rx/WycZ60HOaqLKAi6cHRKKI7zxWbJ31MhntmtwMoaTeF7XFH9hhBp8vITaMidfljRQ6eYWCKkaTK+ykVJHP2A==";
  };
  "function-bind@1.1.2" = fetchurl {
    url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
    hash = "sha512-7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
  };
  "get-east-asian-width@1.6.0" = fetchurl {
    url = "https://registry.npmjs.org/get-east-asian-width/-/get-east-asian-width-1.6.0.tgz";
    hash = "sha512-QRbvDIbx6YklUe6RxeTeleMR0yv3cYH6PsPZHcnVn7xv7zO1BHN8r0XETu8n6Ye3Q+ahtSarc3WgtNWmehIBfA==";
  };
  "get-intrinsic@1.3.0" = fetchurl {
    url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.3.0.tgz";
    hash = "sha512-9fSjSaos/fRIVIp+xSJlE6lfwhES7LNtKaCBIamHsjr2na1BiABJPo0mOjjz8GJDURarmCPGqaiVg5mfjb98CQ==";
  };
  "get-proto@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/get-proto/-/get-proto-1.0.1.tgz";
    hash = "sha512-sTSfBjoXBp89JvIKIefqw7U2CCebsc74kiY6awiGogKtoSGbgjYE/G/+l9sF3MWFPNc9IcoOC4ODfKHfxFmp0g==";
  };
  "gopd@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/gopd/-/gopd-1.2.0.tgz";
    hash = "sha512-ZUKRh6/kUFoAiTAtTYPZJ3hw9wNxx+BIBOijnlG9PnrJsCcSjs1wyyD6vJpaYtgnzDrKYRSqf3OO6Rfa93xsRg==";
  };
  "has-symbols@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.1.0.tgz";
    hash = "sha512-1cDNdwJ2Jaohmb3sg4OmKaMBwuC48sYni5HUw2DvsC8LjGTLK9h+eb1X6RyuOHe4hT0ULCW68iomhjUoKUqlPQ==";
  };
  "hasown@2.0.4" = fetchurl {
    url = "https://registry.npmjs.org/hasown/-/hasown-2.0.4.tgz";
    hash = "sha512-T2UbfbBEF32wiepXIsMlTW9+dDYC6wMh/t/vYA4tuOMKqWz/n3vr1NFSxQiyP+zk2mXsoMA/i/7qV6LKut1t1A==";
  };
  "hono@4.13.5" = fetchurl {
    url = "https://registry.npmjs.org/hono/-/hono-4.13.5.tgz";
    hash = "sha512-O6+/eCYRkzzzy0rPWwKLiGBR1nFuUPZynnwjxN1MBA62NNqbT0wQEzQyK2gSO5yDIDB336sXQleAhOHrzlYyKw==";
  };
  "http-errors@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/http-errors/-/http-errors-2.0.1.tgz";
    hash = "sha512-4FbRdAX+bSdmo4AUFuS0WNiPz8NgFt+r8ThgNWmlrjQjt1Q7ZR9+zTlce2859x4KSXrwIsaeTqDoKQmtP8pLmQ==";
  };
  "iconv-lite@0.7.3" = fetchurl {
    url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.7.3.tgz";
    hash = "sha512-IKXpvIzjnC9XTAUbVBcMfGS0EPaIXtW6v+zr+RRp+hqULEpo0owZax6wyRwPOJbWbzjYspQwusTsfVr0ifh4uQ==";
  };
  "inherits@2.0.4" = fetchurl {
    url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
    hash = "sha512-k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
  };
  "ip-address@10.7.0" = fetchurl {
    url = "https://registry.npmjs.org/ip-address/-/ip-address-10.7.0.tgz";
    hash = "sha512-BGFsyJd5mpXp3rK6jIdADLNgpJUK1jnjzvYF8lK+VyDab9JAmqN0YOKDdP17HlgKb2+ehPgDc8EtnRLbGCAMhA==";
  };
  "ipaddr.js@1.9.1" = fetchurl {
    url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.9.1.tgz";
    hash = "sha512-0KI/607xoxSToH7GjN1FfSbLoU0+btTicjsQSWQlh/hZykN8KpmMf7uYwPW3R+akZ6R/w18ZlXSHBYXiYUPO3g==";
  };
  "is-promise@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-promise/-/is-promise-4.0.0.tgz";
    hash = "sha512-hvpoI6korhJMnej285dSg6nu1+e6uxs7zG3BYAm5byqDsgJNWwxzM6z6iZiAgQR4TJ30JmBTOwqZUw3WlyH3AQ==";
  };
  "isexe@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
    hash = "sha512-RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
  };
  "jose@6.2.10" = fetchurl {
    url = "https://registry.npmjs.org/jose/-/jose-6.2.10.tgz";
    hash = "sha512-iiW7J9qRFlGxvCOIBDBDxFePQSn7ZMAnrYGhrrOo6siO/MIqwfyilLR27pkfDgUk+raLuzADS8A3S/KLBisc0g==";
  };
  "json-schema-to-ts@3.1.1" = fetchurl {
    url = "https://registry.npmjs.org/json-schema-to-ts/-/json-schema-to-ts-3.1.1.tgz";
    hash = "sha512-+DWg8jCJG2TEnpy7kOm/7/AxaYoaRbjVB4LFZLySZlWn8exGs3A4OLJR966cVvU26N7X9TWxl+Jsw7dzAqKT6g==";
  };
  "json-schema-traverse@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz";
    hash = "sha512-NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==";
  };
  "json-schema-typed@8.0.2" = fetchurl {
    url = "https://registry.npmjs.org/json-schema-typed/-/json-schema-typed-8.0.2.tgz";
    hash = "sha512-fQhoXdcvc3V28x7C7BMs4P5+kNlgUURe2jmUT1T//oBRMDrqy1QPelJimwZGo7Hg9VPV3EQV5Bnq4hbFy2vetA==";
  };
  "marked@17.0.1" = fetchurl {
    url = "https://registry.npmjs.org/marked/-/marked-17.0.1.tgz";
    hash = "sha512-boeBdiS0ghpWcSwoNm/jJBwdpFaMnZWRzjA6SkUMYb40SVaN1x7mmfGKp0jvexGcx+7y2La5zRZsYFZI6Qpypg==";
  };
  "math-intrinsics@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/math-intrinsics/-/math-intrinsics-1.1.0.tgz";
    hash = "sha512-/IXtbwEk5HTPyEwyKX6hGkYXxM9nbj64B+ilVJnC/R6B0pH5G4V3b0pVbL7DBj4tkhBAppbQUlf6F6Xl9LHu1g==";
  };
  "media-typer@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/media-typer/-/media-typer-1.1.1.tgz";
    hash = "sha512-yz3xRaG20c6/BOzvYoDaGtPmGscs7YivItZEEqe6GbwNfHuxu9YNmvnEkMzKldAGY4/80pRcQRZSEnhquk9XuQ==";
  };
  "merge-descriptors@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-2.0.0.tgz";
    hash = "sha512-Snk314V5ayFLhp3fkUREub6WtjBfPdCPY1Ln8/8munuLuiYhsABgBVWsozAG+MWMbVEvcdcpbi9R7ww22l9Q3g==";
  };
  "mime-db@1.54.0" = fetchurl {
    url = "https://registry.npmjs.org/mime-db/-/mime-db-1.54.0.tgz";
    hash = "sha512-aU5EJuIN2WDemCcAp2vFBfp/m4EAhWJnUNSSw0ixs7/kXbd6Pg64EmwJkNdFhB8aWt1sH2CTXrLxo/iAGV3oPQ==";
  };
  "mime-types@3.0.2" = fetchurl {
    url = "https://registry.npmjs.org/mime-types/-/mime-types-3.0.2.tgz";
    hash = "sha512-Lbgzdk0h4juoQ9fCKXW4by0UJqj+nOOrI9MJ1sSj4nI8aI2eo1qmvQEie4VD1glsS250n15LsWsYtCugiStS5A==";
  };
  "ms@2.1.3" = fetchurl {
    url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
    hash = "sha512-6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
  };
  "msgpackr-extract@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/msgpackr-extract/-/msgpackr-extract-3.0.4.tgz";
    hash = "sha512-4kmO/MdyUIkLIvTPr8VHLil4AtoKIoniWPIEk5+CDy0xnWC84azhSFmuJ7PxZdsYtiP5kEeQsORAVIeMgxT+Hw==";
  };
  "msgpackr@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/msgpackr/-/msgpackr-2.1.0.tgz";
    hash = "sha512-p/pBCVO63CsvvpkomUnNNag6+n38rULuDA6HHe70o2gtC8ODI52foF/4ko2qQcp6OiErJXTmrZeXmsGGHsIQNQ==";
  };
  "negotiator@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/negotiator/-/negotiator-1.1.0.tgz";
    hash = "sha512-NMPBRMJgiQHjbd8phG3Vebdx4kZ1H121rbl5IkMqeOsahptB9BKo/d7oJ3zTXqTgagn2bWlNSXkh0QUGM31RYg==";
  };
  "node-gyp-build-optional-packages@5.2.2" = fetchurl {
    url = "https://registry.npmjs.org/node-gyp-build-optional-packages/-/node-gyp-build-optional-packages-5.2.2.tgz";
    hash = "sha512-s+w+rBWnpTMwSFbaE0UXsRlg7hU4FjekKU4eyAih5T8nJuNZT1nNsskXpxmeqSK9UzkBl6UgRlnKc8hz8IEqOw==";
  };
  "object-assign@4.1.1" = fetchurl {
    url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
    hash = "sha512-rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
  };
  "object-inspect@1.13.4" = fetchurl {
    url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.13.4.tgz";
    hash = "sha512-W67iLl4J2EXEGTbfeHCffrjDfitvLANg0UlX3wFUUSTx92KXRFegMHUVgSqE+wvhAbi4WqjGg9czysTV2Epbew==";
  };
  "on-finished@2.4.1" = fetchurl {
    url = "https://registry.npmjs.org/on-finished/-/on-finished-2.4.1.tgz";
    hash = "sha512-oVlzkg3ENAhCk2zdv7IJwd/QUD4z2RxRwpkcGY8psCVcCYZNq4wYnVWALHM+brtuJjePWiYF/ClmuDr8Ch5+kg==";
  };
  "once@1.4.0" = fetchurl {
    url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
    hash = "sha512-lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
  };
  "parseurl@1.3.3" = fetchurl {
    url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.3.tgz";
    hash = "sha512-CiyeOxFT/JZyN5m0z9PfXw4SCBJ6Sygz1Dpl0wqjlhDEGGBP1GnsUVEL0p63hoG1fcj3fHynXi9NYO4nWOL+qQ==";
  };
  "path-key@3.1.1" = fetchurl {
    url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
    hash = "sha512-ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
  };
  "path-to-regexp@8.4.2" = fetchurl {
    url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-8.4.2.tgz";
    hash = "sha512-qRcuIdP69NPm4qbACK+aDogI5CBDMi1jKe0ry5rSQJz8JVLsC7jV8XpiJjGRLLol3N+R5ihGYcrPLTno6pAdBA==";
  };
  "pkce-challenge@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/pkce-challenge/-/pkce-challenge-5.0.1.tgz";
    hash = "sha512-wQ0b/W4Fr01qtpHlqSqspcj3EhBvimsdh0KlHhH8HRZnMsEa0ea2fTULOXOS9ccQr3om+GcGRk4e+isrZWV8qQ==";
  };
  "proxy-addr@2.0.7" = fetchurl {
    url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.7.tgz";
    hash = "sha512-llQsMLSUDUPT44jdrU/O37qlnifitDP+ZwrmmZcoSKyLKvtZxpyV0n2/bD/N4tBAAZ/gJEdZU7KMraoK1+XYAg==";
  };
  "pure-rand@8.4.2" = fetchurl {
    url = "https://registry.npmjs.org/pure-rand/-/pure-rand-8.4.2.tgz";
    hash = "sha512-vvuOGgcuPJAirlHvuQw1TrOiw7ptaIXXmIbNuiNOY6lNGJJH49PQ1Kj4nd783nPdQhQdicgOjVI2yI/9BD6/Ng==";
  };
  "qs@6.16.0" = fetchurl {
    url = "https://registry.npmjs.org/qs/-/qs-6.16.0.tgz";
    hash = "sha512-h6fhOIaRrID2CbEY2fqs+7t+UXZo+MLAnU5gRIq85uFtdiUPCdsApMlHhXogKVM4HM2DVbIjGNTTYH2OcmP1vA==";
  };
  "range-parser@1.3.0" = fetchurl {
    url = "https://registry.npmjs.org/range-parser/-/range-parser-1.3.0.tgz";
    hash = "sha512-hek2mFQpPuI4E1BBKrSto+BU3e3x4xuarsbiwr3+lf7p44juvFMV0XFWQAP3xUyqXA4RrXLIoaSUGbSt056ZMw==";
  };
  "raw-body@3.0.2" = fetchurl {
    url = "https://registry.npmjs.org/raw-body/-/raw-body-3.0.2.tgz";
    hash = "sha512-K5zQjDllxWkf7Z5xJdV0/B0WTNqx6vxG70zJE4N0kBs4LovmEYWJzQGxC9bS9RAKu3bgM40lrd5zoLJ12MQ5BA==";
  };
  "require-from-string@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz";
    hash = "sha512-Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==";
  };
  "router@2.2.0" = fetchurl {
    url = "https://registry.npmjs.org/router/-/router-2.2.0.tgz";
    hash = "sha512-nLTrUKm2UyiL7rlhapu/Zl45FwNgkZGaCpZbIHajDYgwlJCOzLSk+cIPAnsEqV955GjILJnKbdQC1nVPz+gAYQ==";
  };
  "safer-buffer@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
    hash = "sha512-YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
  };
  "send@1.2.1" = fetchurl {
    url = "https://registry.npmjs.org/send/-/send-1.2.1.tgz";
    hash = "sha512-1gnZf7DFcoIcajTjTwjwuDjzuz4PPcY2StKPlsGAQ1+YH20IRVrBaXSWmdjowTJ6u8Rc01PoYOGHXfP1mYcZNQ==";
  };
  "serve-static@2.2.1" = fetchurl {
    url = "https://registry.npmjs.org/serve-static/-/serve-static-2.2.1.tgz";
    hash = "sha512-xRXBn0pPqQTVQiC8wyQrKs2MOlX24zQ0POGaj0kultvoOCstBQM5yvOhAVSUwOMjQtTvsPWoNCHfPGwaaQJhTw==";
  };
  "setprototypeof@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.2.0.tgz";
    hash = "sha512-E5LDX7Wrp85Kil5bhZv46j8jOeboKq5JMmYM3gVGdGH8xFpPWXUMsNrlODCrkoxMEeNi/XZIwuRvY4XNwYMJpw==";
  };
  "shebang-command@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
    hash = "sha512-kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
  };
  "shebang-regex@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
    hash = "sha512-7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
  };
  "side-channel-list@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/side-channel-list/-/side-channel-list-1.0.1.tgz";
    hash = "sha512-mjn/0bi/oUURjc5Xl7IaWi/OJJJumuoJFQJfDDyO46+hBWsfaVM65TBHq2eoZBhzl9EchxOijpkbRC8SVBQU0w==";
  };
  "side-channel-map@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/side-channel-map/-/side-channel-map-1.0.1.tgz";
    hash = "sha512-VCjCNfgMsby3tTdo02nbjtM/ewra6jPHmpThenkTYh8pG9ucZ/1P8So4u4FGBek/BjpOVsDCMoLA/iuBKIFXRA==";
  };
  "side-channel-weakmap@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/side-channel-weakmap/-/side-channel-weakmap-1.0.2.tgz";
    hash = "sha512-WPS/HvHQTYnHisLo9McqBHOJk2FkHO/tlpvldyrnem4aeQp4hai3gythswg6p01oSoTl58rcpiFAjF2br2Ak2A==";
  };
  "side-channel@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/side-channel/-/side-channel-1.1.1.tgz";
    hash = "sha512-6x6dK6zJdpTzF4sQeNYxwtvBzf6Eg4GtlesS94HOvTudUeyK2WXAaIfmDgsyslYrRBeFIlsi54AYsFGUuhmvrQ==";
  };
  "standardwebhooks@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/standardwebhooks/-/standardwebhooks-1.1.1.tgz";
    hash = "sha512-bCbX9ZEyFkWPsRz7Bl3NuQUJohmwGSev/yhr7vhaGPlc4AfIrspIRa6cPTBuI1ItmrTDJ4d/S2hCsfe4+vQGnQ==";
  };
  "statuses@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/statuses/-/statuses-2.0.2.tgz";
    hash = "sha512-DvEy55V3DB7uknRo+4iOGT5fP1slR8wQohVdknigZPMpMstaKJQWhwiYBACJE3Ul2pTnATihhBYnRhZQHGBiRw==";
  };
  "string-width@7.2.0" = fetchurl {
    url = "https://registry.npmjs.org/string-width/-/string-width-7.2.0.tgz";
    hash = "sha512-tsaTIkKW9b4N+AEj+SVA+WhJzV7/zMhcSu78mLKWSk7cXMOSHsBKFWUs0fWwq8QyK3MgJBQRX6Gbi4kYbdvGkQ==";
  };
  "strip-ansi@7.1.2" = fetchurl {
    url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.1.2.tgz";
    hash = "sha512-gmBGslpoQJtgnMAvOVqGZpEz9dyoKTCzy2nfz/n8aIFhN/jCE/rCmcxabB6jOOHV+0WNnylOxaxBQPSvcWklhA==";
  };
  "toidentifier@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.1.tgz";
    hash = "sha512-o5sSPKEkg/DIQNmH43V0/uerLrpzVedkUh8tGNvaeXpfpuwjKenlSox/2O/BTlZUtEe+JG7s5YhEz608PlAHRA==";
  };
  "ts-algebra@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/ts-algebra/-/ts-algebra-2.0.0.tgz";
    hash = "sha512-FPAhNPFMrkwz76P7cdjdmiShwMynZYN6SgOujD1urY4oNm80Ou9oMdmbR45LotcKOXoy7wSmHkRFE6Mxbrhefw==";
  };
  "type-is@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/type-is/-/type-is-2.1.0.tgz";
    hash = "sha512-faYHw0anBbc/kWF3zFTEnxSFOAGUX9GFbOBthvDdLsIlEoWOFOtS0zgCiQYwIskL9iGXZL3kAXD8OoZ4GmMATA==";
  };
  "typescript@5.9.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
    hash = "sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
  };
  "undici-types@8.3.0" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-8.3.0.tgz";
    hash = "sha512-j375ScV60dom+YkPFIfTLcOiPxkN/buHz5GobjLhixFuANaNs3C9l4GmrWqejgXWJ7BbJcFYpTEUkS1Ge8bpZQ==";
  };
  "unpipe@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
    hash = "sha512-pjy2bYhSsufwWlKwPc+l3cN7+wuJlK6uz0YdJEOlQDbl6jo/YlPi4mb8agUkVC8BF7V8NuzeyPNqRksA3hztKQ==";
  };
  "vary@1.1.2" = fetchurl {
    url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
    hash = "sha512-BNGbWLfd0eUPabhkXUVm0j8uuvREyTh5ovRa/dyow/BqAbZJyC+5fU+IzQOzmAKzYqYRAISoRhdQr3eIZ/PXqg==";
  };
  "web-tree-sitter@0.25.10" = fetchurl {
    url = "https://registry.npmjs.org/web-tree-sitter/-/web-tree-sitter-0.25.10.tgz";
    hash = "sha512-Y09sF44/13XvgVKgO2cNDw5rGk6s26MgoZPXLESvMXeefBf7i6/73eFurre0IsTW6E14Y0ArIzhUMmjoc7xyzA==";
  };
  "which@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
    hash = "sha512-BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
  };
  "wrappy@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
    hash = "sha512-l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
  };
  "ws@8.21.3" = fetchurl {
    url = "https://registry.npmjs.org/ws/-/ws-8.21.3.tgz";
    hash = "sha512-201TZ/kPWxoPr/OKWjquZR1SWKXcvxdH+e1xrx89b3YbmzLMFCLfnaG1HFIgWzJOEWZ7MvpK++odZufgYR50Rw==";
  };
  "zod-to-json-schema@3.25.2" = fetchurl {
    url = "https://registry.npmjs.org/zod-to-json-schema/-/zod-to-json-schema-3.25.2.tgz";
    hash = "sha512-O/PgfnpT1xKSDeQYSCfRI5Gy3hPf91mKVDuYLUHZJMiDFptvP41MSnWofm8dnCm0256ZNfZIM7DSzuSMAFnjHA==";
  };
  "zod@4.5.4" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-4.5.4.tgz";
    hash = "sha512-sC95tT5iHHH9gtpj6A81kh+NEaRAUFN+qlUPDUbRfOMvNf5QCBqsb3WgvnpVtK5Y+4UfA6KqufotuTvMGiTlsA==";
  };
}